services:
  - type: web
    name: telegram-webhook
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8356418414:AAGKhqf58E4ob4K_a53MjwR4dGHCCBPXYME"
      - key: TELEGRAM_CHAT_ID
        value: "-4827525419"
